### ISSUE TITLE
TypeScript issues

### ISSUE THREAD

**Issue by syuilo** [fastify/fastify-cookie#224] opened 2022-12-06 05:27 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.10.2

### Plugin version

8.3.0

### Node.js version

18.12.1

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11

### Description

There is a type definition problem when trying to use this plugin in TypeScript.
- I get an error when registering this plugin.
- The types of additional properties such as cookies are not added to `request`.

![image](https://user-images.githubusercontent.com/4439005/205823819-7edd156b-ac8d-47e7-a04b-0fa189d00315.png)

### Steps to Reproduce

1. import fastify and fastify/cookie
2. register the plugin

### Expected Behavior

No type errors

**Comment by syuilo** [comment] 2022-12-06 05:29
My tsconfig.json

``` json
{
	"compilerOptions": {
		"allowJs": true,
		"noEmitOnError": false,
		"noImplicitAny": true,
		"noImplicitReturns": true,
		"noUnusedParameters": false,
		"noUnusedLocals": false,
		"noFallthroughCasesInSwitch": true,
		"declaration": false,
		"sourceMap": false,
		"target": "es2021",
		"module": "es2022",
		"moduleResolution": "node",
		"allowSyntheticDefaultImports": true,
		"removeComments": false,
		"noLib": false,
		"strict": true,
		"strictNullChecks": true,
		"strictPropertyInitialization": false,
		"skipLibCheck": true,
		"experimentalDecorators": true,
		"emitDecoratorMetadata": true,
		"resolveJsonModule": true,
		"isolatedModules": true,
		"rootDir": "./src",
		"baseUrl": "./",
		"paths": {
			"@/*": [
				"./src/*"
			]
		},
		"outDir": "./built",
		"types": [
			"node"
		],
		"typeRoots": [
			"./node_modules/@types",
			"./src/@types"
		],
		"lib": [
			"esnext"
		]
	},
	"compileOnSave": false,
	"include": [
		"./src/**/*.ts"
	],
}

```

**Comment by climba03003** [comment] 2022-12-06 05:54
I cannot reproduce the problem.
But, I would recommend to install `@types/node` and never ever use `typeRoots` and `types` if you really know what you are doing.

**Comment by syuilo** [comment] 2022-12-06 08:11
`@types/node` is already installed. Also, removing `typeRoots` and `types` but continue to have errors.

**Comment by syuilo** [comment] 2022-12-06 08:11
Full error log
```
No overload matches this call.
  Overload 1 of 3, '(plugin: FastifyPluginCallback<{}, RawServerDefault, FastifyTypeProvider>, opts?: FastifyRegisterOptions<{}> | undefined): FastifyInstance<...> & PromiseLike<...>', gave the following error.
    Argument of type 'FastifyCookie' is not assignable to parameter of type 'FastifyPluginCallback<{}, RawServerDefault, FastifyTypeProvider>'.
      Type 'FastifyCookie' provides no match for the signature '(instance: FastifyInstance<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, FastifyTypeProvider>, opts: {}, done: (err?: Error | undefined) => void): void'.
  Overload 2 of 3, '(plugin: FastifyPluginAsync<{}, RawServerDefault, FastifyTypeProvider>, opts?: FastifyRegisterOptions<{}> | undefined): FastifyInstance<...> & PromiseLike<...>', gave the following error.
    Argument of type 'FastifyCookie' is not assignable to parameter of type 'FastifyPluginAsync<{}, RawServerDefault, FastifyTypeProvider>'.
      Type 'FastifyCookie' provides no match for the signature '(instance: FastifyInstance<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, FastifyTypeProvider>, opts: {}): Promise<...>'.
  Overload 3 of 3, '(plugin: FastifyPluginCallback<{}, RawServerDefault, FastifyTypeProvider> | FastifyPluginAsync<{}, RawServerDefault, FastifyTypeProvider> | Promise<...> | Promise<...>, opts?: FastifyRegisterOptions<...> | undefined): FastifyInstance<...> & PromiseLike<...>', gave the following error.
    Argument of type 'FastifyCookie' is not assignable to parameter of type 'FastifyPluginCallback<{}, RawServerDefault, FastifyTypeProvider> | FastifyPluginAsync<{}, RawServerDefault, FastifyTypeProvider> | Promise<...> | Promise<...>'.ts(2769)
```

**Comment by syuilo** [comment] 2022-12-06 08:14
If you can't reproduce it, you can close this as it is most likely a problem with my environment.

**Comment by climba03003** [comment] 2022-12-06 08:30
> If you can't reproduce it, you can close this as it is most likely a problem with my environment.

I would help if you can provide more detail on environment.
For example, `IDE`, `Package Manager`, etc.
Even better is that provide a reproducible repo with the environment.

`TypeScript` is a very complicated program, it behave very differently with a sightly change of environment or setting.

Closing for now.

**Closed by climba03003** 2022-12-06 08:30 UTC
